# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nping.proto\"\x17\n\x07Message\x12\x0c\n\x04\x61rgs\x18\x01 \x01(\t2>\n\x04Ping\x12\x1a\n\x04Ping\x12\x08.Message\x1a\x08.Message\x12\x1a\n\x04\x42\x61ng\x12\x08.Message\x1a\x08.Messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ping_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=14
  _globals['_MESSAGE']._serialized_end=37
  _globals['_PING']._serialized_start=39
  _globals['_PING']._serialized_end=101
# @@protoc_insertion_point(module_scope)
